name: Deployment
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Init terraform
        run: terraform init
      - name: Deploy changes
        run: terraform apply -auto-approve
